будет will
будут would
бы would
был was
было was
во in
всем everything
всеми all
всех everyone
всяких all
всякого anyone
для for
каждого everyone
какого which
какой which
какому which
какую which
которое which
которой which
котором which
которые which
которых which
ли whether
либо either
любую any
любыми by
него him
нежели rather
никакого none
ничто nothing
они they
перед before
по on
пока yet
посредством by
при by
путем way
свое yours
своего yours
своей mine
своем his
своих their
свою your
себе himself
со with
таким such
таких such
такого this
такой such
тем those
тех those
то that
того that
том that
что that
чтобы to
эта this
этим by
этих these
это this
этого this
быть be
в to
из of
я I
в in
иметь have
тот that
он he
не not
его his
ей her
Это it
вы you
с with
за for
сделать do
она she
как as
на on
сказать say
в at
ему him
от from
но but
мне me
мой my
идти go
Oни they
все all
от by
этот this
один one
из out
вверх up
знать know
так so
видеть see
мог could
их them
получить get
мы we
лайк like
приходить come
человек man
какие what
делать make
там there
около about
который which
их their
в into
думать think
смотреть look
если if
кто who
когда when
принять take
время time
нет no
назад back
может can
Желать will
ваш your
Больше more
затем then
вниз down
хорошо good
над over
сказать tell
сейчас now
рука hand
немного some
хотеть want
просто just
только only
чем than
путь way
дать give
Другой other
день day
глаз eye
до before
спросить ask
найти find
два two
немного little
долго long
очень very
чувствовать feel
любой any
вещь thing
тоже too
Вот here
никогда never
покидать leave
человек person
старый old
голова head
превратить turn
снова again
через through
четное even
лицо face
много much
от off
нас us
первый first
право right
наш our
как how
где where
после after
его its
женщина woman
далеко away
жизнь life
казаться seem
звонить call
еще still
слышать hear
год year
своя own
работать work
должен should
место place
номер room
стоять stand
должен must
сам himself
вокруг around
дверь door
что-то something
пытаться try
любить love
ночь night
класть put
отличный great
такие such
хранить keep
сидеть sit
прошлой last
начать begin
те those
эти these
слово word
использовать use
нуждаться need
открыть open
держать hold
другой another
самый most
говорить talk
позволить let
на upon
далеко far
без without
Главная home
улыбаться smile
всегда always
голос voice
ребенок child
отец father
гулять walk
молодой young
означать mean
бежать run
хоть though
момент moment
против against
мама mother
название name
говорить speak
много many
разум mind
мало few
принести bring
свет light
закрывать close
Когда-либо ever
двигаться move
друг friend
каждый every
рука arm
три three
довольно enough
становиться become
девушка girl
под under
новый new
конец end
жить live
также also
помогать help
между between
Мир world
упасть fall
начать start
каждый each
ждать wait
смотреть watch
прекратить stop
что-нибудь anything
и and
ступня foot
часть part
маленький small
действительно really
отвечать answer
показывать show
мальчик boy
врать lie
конечно sure
курс course
произойдет happen
верить believe
возвращать return
позади behind
точка point
следующий next
еще yet
сердце heart
воды water
почти almost
установить set
тело body
Зачем why
пройти pass
утро morning
час hour
звук sound
встречаться meet
Бог God
белый white
помнить remember
Добрый kind
надеяться hope
достигать reach
умереть die
жесткий hard
плохой bad
половина half
смеяться laugh
семья family
поскольку since
высоко high
книга book
шаг step
изменить change
вопрос question
через across
следить follow
вместе together
жена wife
тянуть pull
вместе along
Таблица table
играть play
терять lose
большой big
плакать cry
черный black
волосы hair
читать read
фронт front
отправлять send
довольно quite
сломать break
себя myself
должен shall
уже already
минут minute
темно dark
скоро soon
постель bed
к toward
все whole
автомобиль car
окно window
трясти shake
еще else
остальное rest
Деньги money
факт fact
сын son
написать write
Пожар fire
второй second
остаться stay
удивляться wonder
дело case
история story
линия line
расти grow
воздух air
желать wish
думал thought
подниматься rise
наименее least
полный full
ловить catch
вести lead
большой large
появляться appear
все everything
заботиться care
нести carry
смерть death
спать sleep
убить kill
идея idea
отвечать reply
носить wear
стена wall
водить drive
возле near
рисовать draw
плечо shoulder
неделю week
прошлое past
мертвых dead
рано early
смысл sense
рот mouth
скорее rather
нести bear
четыре four
продолжать continue
дерево tree
причина reason
лошадь horse
другие others
порядок order
много lot
трогать touch
круглый round
глубоко deep
письмо letter
скучать Miss
предполагать suppose
сила force
городок town
кушать eat
Чисто clear
жениться marry
бросать throw
страна country
подарок present
внутри inside
этаж floor
платить pay
кивать nod
Палец finger
оставаться remain
слеза tear
улица street
леди lady
Меньше less
страх fear
бизнес business
стул chair
забывать forget
подобрать pick
ожидать expect
красный red
мощность power
заглянуть glance
возможно perhaps
короткая short
земля ground
правда true
губа lip
реальный real
одеваться dress
месяц month
слушать listen
поздно late
школа school
или either
кому whom
низкий low
среди among
муж husband
добавить add
разные different
бросить drop
пить drink
учить learn
незапно suddenly
бумага paper
Сортировать sort
вечер evening
выше above
сто hundred
замечать notice
дочь daughter
офис office
холодно cold
фигура figure
Дорога road
чувство feeling
повесить hang
вырезать cut
число number
отлично fine
город city
поднимать raise
заполнять fill
несколько several
чья whose
бедные poor
определенный certain
план plan
наверное probably
Топ top
вызывать cause
входить enter
готовы ready
синий blue
в within
вперед forward
сестра sister
потратить spend
государство state
бороться fight
сильный strong
целовать kiss
течение during
немного bit
вне outside
ножка leg
дорогая dear
счастливый happy
мечта dream
нота note
неправильно wrong
осознать realize
интерес interest
кровь blood
быстро quickly
объяснить explain
ветер wind
человек human
повелитель Lord
ездить ride
покрывать cover
наклоняться lean
позволять allow
десять ten
сомнение doubt
двадцать twenty
сэр sir
прекрасный beautiful
война war
хорошенький pretty
медленно slowly
возможный possible
беда trouble
посетить visit
шанс chance
толкать push
свободно free
дыхание breath
кусок piece
солнце sun
правда truth
прибывать arrive
учитывать consider
играть act
сам itself
ни nor
кто-нибудь anyone
знак sign
пересечь cross
стакан glass
работа job
заканчивать finish
шептать whisper
учиться study
форма form
легко easy
возраст age
картина picture
шесть six
покупать buy
тишина silence
собака dog
лежать lay
взгляд sight
ухо ear
предлагать offer
корабль ship
сам yourself
к towards
море sea
кольцо ring
обещать promise
поднимать lift
летать fly
тысяча thousand
угадать guess
угол corner
беспокоиться worry
Посмотреть view
проблема problem
рядом beside
Телефон phone
внимание attention
прятаться hide
пропустить miss
посмотреть gaze
полиция police
сохранить save
вечеринка party
английский English
камень stone
Лондон London
странный strange
детка baby
боюсь afraid
боль pain
волна wave
кухня kitchen
Соглашаться agree
бить strike
нажать press
зеленый green
пара couple
парень guy
извиняюсь sorry
опыт experience
до till
американский American
сиденье seat
катиться roll
дуть blow
иногда sometimes
тяжелый heavy
душа soul
важный important
дитя kid
теплый warm
относиться concern
мой mine
позиция position
горячей hot
врач doctor
за beyond
кричать shout
предмет subject
обед dinner
Проверять check
дух spirit
сотрудник officer
тихо quiet
желание desire
Кроме except
представить imagine
приближаться approach
шея neck
мили mile
манера manner
присоединиться join
питание food
строительство building
придерживаться stick
край edge
поле field
природа nature
река river
камень rock
пистолет gun
упомянуть mention
Прямо straight
широкий wide
Компания company
небо sky
выстрелить shoot
дерево wood
ударить hit
танцевать dance
толпа crowd
сжечь burn
человек fellow
выражение expression
коробка box
контроль control
церковь church
вздыхать sigh
каждый everyone
выбирать choose
делиться share
предлагать suggest
король king
родитель parent
отлично nice
скользить slip
строить build
на on|to
около nearly
одежда clothes
доклад report
просто simply
принять accept
наслаждаться enjoy
кожа skin
секрет secret
конечно certainly
игра game
разговор conversation
лодка boat
пустой empty
сегодня today
ад hell
служить serve
мягкий soft
Сбежать escape
тон tone
ненавидеть hate
направление direction
попытка attempt
хотя although
группа group
щека cheek
карман pocket
управлять manage
да yes
искать search
нюхать smell
весна spring
генеральный general
средний middle
оставил left
следующий following
обвинять charge
общественности public
обосноваться settle
удовольствие pleasure
вместо instead
открывать discover
джентльмен gentleman
золото gold
Новости news
колено knee
яркий bright
немедленно immediately
Рады glad
бить beat
быстро fast
расстояние distance
получить receive
место spot
сцена scene
требовать demand
признавать admit
поезд train
животное animal
зал hall
грудь chest
мастер master
кофе coffee
доверять trust
охрана guard
бесшумный silent
эффект effect
тень shadow
петь sing
мешок bag
Французский French
высокий tall
под beneath
искать seek
никто none
Торопить rush
гора mountain
подготовить prepare
солдат soldier
едва hardly
бар bar
усмехнуться grin
история history
чистый clean
продавать sell
брак marriage
действие action
деревня village
член member
будущее future
холм hill
особенно especially
сад garden
милая sweet
дождь rain
персонаж character
путешествовать travel
атака attack
закрыть shut
дым smoke
безопасный safe
пространство space
площадь area
ниже below
ситуация situation
отказать refuse
тридцать thirty
сухой dry
прыгать jump
повторить repeat
дикий wild
закрывать lock
Англия England
впереди ahead
быстрый quick
Рубашка shirt
побеждать win
нос nose
летом summer
горло throat
усилие effort
просто simple
срок term
учить teach
гонка race
медленный slow
обязанность duty
Музыка music
индийский Indian
событие event
цветок flower
помечать mark
птица bird
собирать gather
Мистер Mr
суд court
встреча meeting
кричать scream
шапка hat
карабкаться climb
убийство murder
подходить fit
ни neither
тонкий thin
результат result
торопиться hurry
полный complete
зуб tooth
связать tie
цель purpose
страница page
подходить suit
враг enemy
века century
бороться struggle
обычный usual
объект object
разбудить wake
богатые rich
требовать claim
справедливый fair
общий common
прочность strength
толстый thick
материал stuff
уважение respect
адресовать address
живой living
Семь seven
распознавать recognize
должен ought
поддерживать support
двор yard
Хватать grab
коричневый brown
команда command
присутствие presence
описать describe
Пальто coat
станция station
необходимо necessary
тонуть sink
банка bank
растянуть stretch
идеально perfect
страдать suffer
внезапно sudden
исчезнуть disappear
восемь eight
дорожка path
конкретный particular
распространять spread
темнота darkness
ступенька stair
благодарить thank
движение movement
сложно difficult
магазин shop
бледный pale
принадлежать belong
язык language
специальный special
серьезный serious
напомнить remind
предоставлять provide
узкий narrow
состояние condition
согнуть bend
звезда star
бутылка bottle
ключ key
качаться swing
громко loud
тихо quietly
ошибка mistake
наблюдать observe
замечать remark
красота beauty
внимательно carefully
Ворота gate
стучать knock
скользить slide
знать aware
удалять remove
полностью completely
дерзать dare
служащий servant
кланяться bow
круг circle
запись record
чай tea
сердитый angry
личный personal
облако cloud
правило rule
боевой battle
доска board
частный private
рана wound
натуральный natural
где-то somewhere
вперед forth
вкус taste
чинить fix
существо creature
длина length
хранить store
свежий fresh
вино wine
квартира apartment
случай occasion
образ image
система system
судья judge
язык tongue
фунт pound
кружка cup
создавать create
форма shape
стоимость worth
песня song
производить produce
больной ill
снег snow
уровень level
дурачить fool
следовательно therefore
считать count
больной sick
Социальное social
завтра tomorrow
подробно detail
мнение opinion
привлекать involve
доллар dollar
огромный huge
лить pour
прохладно cool
грудь breast
уставать tire
немного slightly
лагерь camp
пример example
поездка trip
Гостиница hotel
пара pair
рассказ tale
мигать flash
обычно usually
невозможно impossible
ужасный terrible
общество society
украсть steal
мир peace
сообщение message
дело affair
происходить occur
требовать require
башмак shoe
намереваться intend
цвет color
армия army
незнакомец stranger
занятый busy
серый gray
Немецкий German
содержать contain
желтый yellow
карта card
острый sharp
лечить treat
спокойный calm
мяч ball
низ bottom
Опасность danger
все entire
определить determine
просто merely
рыба fish
главный main
рисовать paint
транслировать cast
автор author
шум noise
гнев anger
разница difference
гость guest
подозревать suspect
шок shock
выстрел shot
главный chief
сиять shine
мыть wash
дышать breathe
правительство government
избежать avoid
размещение stage
пятьдесят fifty
отверстие hole
писатель writer
лопнуть burst
выбор choice
серебро silver
воскликнуть exclaim
тип type
крохотный tiny
трава grass
направлять direct
Америка America
замечательный wonderful
упаковать pack
больница hospital
ее hers
осторожно gently
мягко softly
трек track
доказательства evidence
зло evil
раскрыть reveal
существовать exist
тащить drag
молиться pray
знание knowledge
выразить express
зима winter
знакомый familiar
бог god
период period
блок block
очевидно clearly
роптать murmur
после post
поток stream
подмести sweep
обстоятельство circumstance
настаивать insist
четверть quarter
мозг brain
гладкий plain
квартира flat
вопрос issue
база base
наслаждение delight
остров island
Париж Paris
возможность opportunity
завод plant
радость joy
сдвинуть shift
отношения relationship
нож knife
чистить brush
незначительный slight
блин damn
дрожать tremble
обсуждать discuss
различный various
значение value
парк park
секс sex
местный local
молодежь youth
практика practice
закон wet
завтрак breakfast
капитан captain
уничтожить destroy
путешествие journey
воскресенье Sunday
как-то somehow
нахмуриться frown
обернуть wrap
кот cat
связанный bound
комфорт comfort
жест gesture
священник priest
Франция France
обрабатывать handle
небо heaven
свидетель witness
увеличить increase
особенность feature
пнуть kick
предполагать assume
спящий asleep
вспомнить recall
матч match
плотный tight
лес forest
защищать protect
отсутствие lack
компаньон companion
полностью entirely
решение decision
включать include
след trail
пригласить invite
эмоция emotion
кость bone
час o’clock
окружать surround
окончательный final
поверхность surface
ящики dozen
объявить declare
оружие weapon
центр center
преступление crime
вес weight
листва lover
меч sword
хитрость list
дата date
присутствовать attend
речь speech
Кристиан Christian
заверить assure
щелкнуть snap
движение motion
страсть passion
сакэ sake
влияние influence
скорость speed
люди folk
шторм storm
луна moon
кормить feed
политическая political
просить beg
согласиться accord
машина machine
сорок forty
девять nine
выпустить release
север north
дядя uncle
древний ancient
грустный sad
Британская British
слабый faint
двойной double
могила grave
обед lunch
растворимый instant
плита plate
похоронить bury
отлично perfectly
прекрасный lovely
ваш yours
лед ice
отделить separate
кусать bite
грабитель roof
клясться swear
дюймовый inch
водитель driver
зеркало mirror
желудок stomach
являющийся being
получить gain
игнорировать ignore
хорошо okay
ответить respond
никто nobody
напротив opposite
беспокоить bother
устроить arrange
лодка boot
пыли dust
тереть rub
непосредственно directly
пылать glow
кричать yell
человек individual
медсестра nurse
Миссис Mrs
видение vision
гордый proud
сумасшедший mad
власть authority
контакт contact
газета newspaper
рождество Christmas
риск risk
степень degree
бывший former
несколько somewhat
стиль style
кто-то somebody
обладать possess
грузовик truck
интересный interesting
шутка joke
бормотать mutter
свойство property
голый bare
плоть flesh
рельеф relief
колебаться hesitate
адгезия grip
прыгать leap
поставка supply
прерывать interrupt
еда meal
процесс process
женщина female
потеря loss
сигарета cigarette
железо iron
убедить convince
отдельный apart
маскарадный fancy
строка row
электрокардиостимулятор pace
дважды twice
течь flow
пациент patient
притворяться pretend
размер size
едва barely
свадьба wedding
объявить announce
смех laughter
лист sheet
дизайн design
готовить cook
твой thy
колесо wheel
успех success
опасно dangerous
юг south
бодрствующий awake
свободный loose
лоб forehead
палаш broad
пустыня desert
размешать stir
ход stroke
крыло wing
предупредить warn
сложить fold
свая pile
пламя flame
вход entrance
господин lord
плавать sail
представить introduce
гладкий smooth
мощный powerful
стоимость cost
миллиона million
вера faith
проглотить swallow
мост bridge
студент student
измерение measure
слепой blind
все everybody
состояние fortune
должное due
нежный gentle
исследовать examine
сумасшедший crazy
веселье fun
гордость pride
мужчина male
заниматься engage
тест test
рамка frame
реальность reality
аккуратный proper
отражать reflect
бродить wander
представлять represent
ферма farm
команда team
погода weather
трудность difficulty
слабый weak
смысл meaning
полет flight
приятный pleasant
колода deck
аккуратность careful
квадрат square
оправдание excuse
фирма firm
филиал branch
стереть wipe
цена price
оригинал original
двенадцать twelve
адвокат lawyer
след trace
молитва prayer
кто-нибудь anybody
честь honor
колокол bell
подарок gift
Крайстчерч Christ
энергия energy
возможно possibly
привычка habit
готовы willing
качество quality
бросить toss
придираться fault
опустить lower
конечно surely
по-видимому apparently
спорить argue
начало beginning
handsomeness handsome
глубоко deeply
обвинять blame
протестовать protest
заключенный prisoner
указать indicate
чай thee
крутить twist
куртка jacket
герой hero
везение luck
содержание content
сообщить inform
предотвратить prevent
счастье happiness
действительно truly
развивать develop
подбородок chin
разрушить ruin
взломать crack
лидер leader
вчера yesterday
пятнадцать fifteen
деревянный wooden
доставить deliver
агент agent
материал material
ответ response
прохождение passage
глупый stupid
мода fashion
задача task
любопытный curious
преуспеть succeed
мудрый wise
сумма amount
телефон telephone
отрицать deny
копать dig
закон law
призвать urge
навсегда forever
сообщество community
физическое physical
источник source
пальма palm
учитель teacher
рабыня slave
чувак fat
предпочитать prefer
военные military
хлеб bread
ссылаться refer
кабина cabin
красочно fully
неспособный unable
сопровождать accompany
продолжить proceed
обменять exchange
масса mass
запрос request
установить establish
нечетный odd
берег shore
вести guide
золотой golden
сами ourselves
простой mere
отношение relation
угрожать threaten
скорость rate
проклинать curse
нести beer
отдаленный distant
очевидный obvious
комментарий comment
благородный noble
преимущество advantage
озлобленность spite
затор file
возможность possibility
проводить conduct
исчезать fade
современный modern
сосредоточиться focus
экран screen
существование existence
монтировать mount
песок sand
жертва victim
наконечник tip
ярость rage
счетчик counter
последний latter
напугать scare
авария accident
впечатление impression
всматриваться peer
гей gay
скручиваться curl
собирать collect
маршировать march
отображать display
пляж beach
тетка aunt
удобный comfortable
дрейфовать drift
жалость pity
волнение excitement
очевидно obviously
торговля trade
клуб club
клетка cell
здоровье health
запад west
кожа leather
грубый rough
задыхаться gasp
выполнять perform
мизинец pink
группа band
предложение sentence
настроение mood
статья article
цепь chain
каретка carriage
произнести utter
тень shade
самолет plane
колледж college
прощать forgive
стихотворение poem
веревка rope
свет lamp
пример instance
чистый pure
загрузить load
захватить seize
задний rear
честный honest
главный major
сходный similar
деятельность activity
повторить echo
занимать occupy
известный famous
озабоченный anxious
смешной funny
аргумент argument
дьявол devil
уверенность confidence
сожалеть regret
совершать commit
пот sweat
русский Russian
диапазон range
восстановить recover
ужас horror
безопасность security
экипаж crew
реветь roar
рассвет dawn
нация nation
металл metal
нервное nervous
тюрьма prison
отказаться abandon
где-нибудь anywhere
поэт poet
его his
травить grasp
отношение attitude
заявление statement
обнаженный naked
счет bill
чело brow
мораль moral
Ролл role
много plenty
карьера career
хвост tail
рождение birth
применять apply
официальный official
связать relate
судьба fate
проект project
долина valley
воображение imagination
напугать frighten
рынок market
кулак fist
намерение intention
соединение connection
серия series
мужество courage
башня tower
озеро lake
выйти emerge
ставить bet
фильм movie
юбка skirt
плакать weep
камера chamber
суд trial
магия magic
двигатель engine
спасибо thanks
письменность writing
кнопка button
фильм film
охотиться hunt
обычный ordinary
продлить extend
сохранить spare
теория theory
нормальный normal
неуклонный steady
предоставлять grant
июнь June
иудей Jew
текст text
абсолютно absolutely
честь honour
плавать float
тайна mystery
сезон season
владелец owner
цвет colour
совет advice
партнер partner
восхищаться admire
крышка cap
свобода freedom
заслужить deserve
приветствовать greet
обнимать hug
персонал staff
толкать thrust
впоследствии afterwards
правильный correct
зависеть depend
плавать swim
бассейн pool
сигнал signal
невинный innocent
пятка heel
generelt generally
занавес curtain
владение possession
фотография photograph
едва scarcely
радио radio
родной native
серый grey
форма blanket
интервью interview
разрешить permit
грязный dirty
позор shame
прекратить cease
яйцо egg
объяснение explanation
вагон wagon
аудитория audience
ужасный awful
труба pipe
напрягать strain
художник artist
сжать squeeze
роман Roman
обжаловать appeal
ткань cloth
террор terror
объем volume
восток east
раздел section
беспокоить disturb
ранг rank
дружеский friendly
голодный hungry
ползти creep
посетитель visitor
везде everywhere
религиозная religious
получить obtain
мясо meat
горничная maid
юстиция justice
прогресс progress
круг lap
наверх upstairs
вера belief
подключить connect
роман novel
призрак ghost
стремиться aim
бросать fling
суббота Saturday
хирургия operation
рысь despite
талия waist
молоко milk
обнимать embrace
ванная bathroom
горшок pot
встретить encounter
имущество estate
предыдущий previous
крутиться spin
фантастика fiction
большой grand
ловушка trap
влиять affect
трюк trick
шелк silk
супов supper
пьяный drunk
намек hint
заменить replace
возмущенно harm
фрукты fruit
компьютер computer
локоть elbow
спускаться descend
крыльцо porch
раздуваться swell
окна upper
полицейский cop
дед grandfather
осуществление exercise
библиотека library
мускул muscle
заморозить freeze
расстраивать upset
жаловаться complain
Европа Europe
благоприятствовать favor
корень root
зверь beast
возникать arise
вызов challenge
душ shower
греческий Greek
половой sexual
строка string
предел limit
ресторан restaurant
религия religion
давление pressure
исчезнуть vanish
благодать grace
огромный vast
признаться confess
жертвоприношение sacrifice
прибытие arrival
дергаться jerk
урок lesson
тазобедренный hip
отпуск lad
масло oil
шаблон pattern
регулярный regular
винтовка rifle
удачливый lucky
задница ass
тусклый dull
сознательный conscious
беспорядок mess
элемент element
стонать groan
konsekvens consequence
баланс balance
принцип principle
любовь affection
ток current
свеча candle
дерьмо shit
блохи flee
высота height
акции stock
рыцарь knight
часы clock
замок castle
забор fence
виновный guilty
разрешить resolve
расслабиться relax
храм temple
кроме besides
журнал magazine
любимый favorite
сидящий seated
апреля April
традиция tradition
горький bitter
ценить appreciate
наука science
популярный popular
бабушка grandmother
модель model
ежедневно daily
обсуждение discussion
принц prince
очарование charm
раздеть strip
единообразный uniform
описание description
потолок ceiling
куст bush
ЛОЖЬ FALSE
Майки interested
тесно closely
цепляться cling
скамья bench
преследовать pursue
отважный brave
удовлетворение satisfaction
ползать crawl
автобус bus
литературный literary
кровавый bloody
сравнивать compare
иностранные foreign
предложить propose
перо pen
спрашивать inquire
горе grief
помощь aid
дружба friendship
врезаться crash
приключение adventure
бороться stride
культура culture
луч beam
безопасность safety
марш March
очки glasses
evne ability
отлично excellent
твердо firmly
понимание understanding
сталь steel
нерв nerve
ангел angel
гигант giant
подозрительность suspicion
неизвестный unknown
испугаться startle
равный equal
палатка tent
смеяться gleam
умный smart
поколение generation
сопротивляться resist
в per
когда-либо whenever
заклинание spell
реакция reaction
образование education
доказательство proof
возбуждать excite
сиять blink
взбить whip
идентифицировать identify
чаша bowl
разоблачить expose
предупреждение warning
глубина depth
глава chapter
расположение arrangement
болеть ache
потягивать sip
сильно heavily
итальянский Italian
бровь eyebrow
посмеиваться chuckle
дворец palace
серьезно seriously
отступать retreat
картина painting
viktigheten importance
дополнительный extra
королева queen
молча silently
запястье wrist
отстоять slam
ответственность responsibility
челюсть jaw
плохо badly
пассажир passenger
открытие opening
июль July
умение skill
миссия mission
преследовать chase
обычай custom
метод method
корова cow
нетерпеливый eager
воин warrior
вцепиться clutch
воспринимать perceive
пещера cave
кредит credit
похвала praise
способный capable
нанять hire
версия version
сосед neighbor
скрывать conceal
сверлить bore
симпатия sympathy
проволока wire
любопытство curiosity
ремень belt
относительный relative
понятие notion
захватить capture
переключаться switch
почта mail
кушетка couch
коридор corridor
отойти depart
немедленно instantly
испанский Spanish
угроза threat
китайский Chinese
очень highly
нанять employ
ссылка link
отсутствие absence
отчаяние despair
структура structure
одиноко lonely
благодарный grateful
вывести withdraw
карта map
министр minister
подушка pillow
видимый visible
судно vessel
любовница mistress
прикрепить attach
нежный delicate
запутать confuse
профессиональный professional
тепло warmth
сломанный broken
исчерпать exhaust
глупый silly
детектив detective
печаль sorrow
седло saddle
повреждение damage
хороший rare
предать betray
спать slap
признать acknowledge
платье gown
твердый solid
очень extremely
фраза phrase
гвоздь nail
очистить rent
поддерживать maintain
августейший August
работник worker
пуля bullet
магистральный trunk
konkluderer conclusion
пистолет pistol
коттедж cottage
блестящий brilliant
гражданин citizen
быстро rapidly
свистеть whistle
отчаянный desperate
слегка lightly
аспект aspect
путаница confusion
уродливый ugly
интеллект intelligence
кровать sofa
пролить shed
дорогой darling
папа dad
кривая curve
ветер breeze
Лика equally
лента tape
рисковать venture
поцарапать scratch
нюх scent
привлечь attract
развитие development
приколоть pin
пихать shove
медицинская medical
скат slope
естественно naturally
умственный mental
защищать defend
заработать earn
молиться bid
камера camera
грязь dirt
оболочка shell
участок plot
корона crown
успешный successful
добродетель virtue
наводнение flood
Рим Rome
кошелек purse
поэзия poetry
поп pop
живот belly
общий total
подтвердить confirm
решение judgment
enorme enormous
раздавить crush
баскетбол basket
укрытие shelter
погладить pat
ansvarlig responsible
сознание consciousness
senaste recent
делить divide
преступник criminal
драгоценный precious
довольно fairly
поощрять encourage
граница border
океан ocean
листья blade
отражение reflection
похороны funeral
отдел department
необычный unusual
автомобиль vehicle
страшиться dread
фон background
стандарт standard
телевидение television
обвинять accuse
полностью totally
выгода benefit
обеденный dining
