άλλες other
άλλη another
άλλους others
άλλων alia
αυτά these
αυτές these
αυτού of_this
αυτών of_them
γάμου wedlock
εκείνη her
εναντίον against
ενός single
εξαιτίας owing
έχει have
έχουν have
θα will
ίση equal
καμία wickedness
κανένα none
μην prevent
μια a
μιας one
οι the
οποία which
οποιαδήποτε any
οποίας which
οποίες which
οποίο which
οποιοδήποτε any_one
οποιονδήποτε anyone
παρά spite
που where
στα Sta
στη in
στην in
Στην In
στις on
στον Sto
στους Sto
τα the
τέτοια sort_of_thing
τη set
την the
τις the
τον ton
των of
υπό conditional
φύλο sex
ως by_way
ωσότου until
ώστε in_order
ο the
και and
του of
ένα a
εγώ i
σε in
ότι that
αυτός he
δεν not
του his
αυτήν her
το it
εσύ you
με with
για for
αυτή she
επί on
στο at
αυτόν him
από from
αλλά but
μου me
μου my
αυτοί they
όλα all
με by
αυτό this
ένας one
έξω out
πάνω up
έτσι so
ένα an
ή or
τους them
εμείς we
σαν like
άνδρας man
τι what
εκεί there
σε into
σκέφτομαι think
αν if
πότε when
χρόνος time
όχι no
πίσω back
περισσότερο more
έπειτα then
κάτω down
καλός good
τώρα now
χέρι hand
μερικοί some
μόλις just
μόνο only
από than
τρόπος way
άλλα other
ημέρα day
μάτι eye
πριν before
δύο two
λίγο little
μακρύς long
πολύ very
νιώθω feel
όποιος any
πράγμα thing
πολύ too
εδώ here
ποτέ never
πρόσωπο person
παλαιός old
κεφάλι head
πάλι again
πρόσωπο face
πολύ much
μας us
πρώτα first
σωστά right
μας our
πως how
όπου where
μετά after
του its
γυναίκα woman
μακριά away
ζωη life
ακόμη still
έτος year
πρέπει should
θέση place
δωμάτιο room
καλά well
στέκομαι stand
γύρω around
θύρα door
κάτι something
σπίτι house
νύχτα night
μεγάλος great
τέτοιος such
τελευταίος last
επειδή because
εκείνοι those
λέξη word
χρησιμοποιώ use
αλλο another
ενώ while
πλέον most
μακριά far
χωρίς without
σπίτι home
πάντα always
φωνή voice
παιδί child
πατέρας father
νέος young
τίποτα nothing
τρέχω run
στιγμή moment
κατά against
μητέρα mother
ίδιο same
όνομα name
πολλά many
μυαλό mind
λίγοι few
φως light
πλευρά side
πάντα ever
φίλος friend
κάθε every
μπράτσο arm
τρία three
αρκετά enough
κορίτσι girl
νέος new
τέλος end
επίσης also
μεταξύ between
κόσμος world
καθε each
περιμένω wait
οτιδήποτε anything
πόδι foot
μέρος part
μικρό small
μέχρι until
πραγματικά really
απαντώ answer
αγόρι boy
εαυτήν herself
σίγουρος sure
πιστεύω believe
πίσω behind
σημείο point
επόμενο next
ακόμη yet
καρδιά heart
νερό water
σχεδόν almost
σώμα body
γιατί why
πρωί morning
ώρα hour
ήχος sound
θεός god
λευκό white
είδος kind
πεθαίνω die
σκληρά hard
κακό bad
ήμισυ half
γελώ laugh
οικογένεια family
από since
υψηλός high
βιβλίο book
ύλη matter
βήμα step
ερώτηση question
απέναντι across
ακολουθώ follow
μαζί together
γυναίκα wife
τραπέζι table
μεγάλο big
μαύρος black
μαλλιά hair
εμπρός front
αρκετά quite
να shall
ήδη already
λεπτό minute
σκοτάδι dark
σύντομα soon
κρεβάτι bed
προς toward
ολόκληρος whole
αυτοκίνητο car
παράθυρο window
αλλού else
υπόλοιπο rest
χρήματα money
γεγονός fact
υιός son
φωτιά fire
δεύτερος second
υπόθεση case
ιστορία story
γραμμή line
αέρας air
σκέψη thought
ανεβαίνω rise
ελάχιστα least
γεμάτος full
μεγάλο large
θάνατος death
ιδέα idea
τείχος wall
κοντά near
ώμος shoulder
εβδομάδα week
νεκρός dead
νωρίς early
μόνος alone
έννοια sense
στόμα mouth
μάλλον rather
τέσσερα four
δέντρο tree
αδελφός brother
λόγος reason
άλογο horse
σειρά order
παρτίδα lot
πέντε five
στρογγυλό round
βαθύς deep
γράμμα letter
δεσποινίδα miss
δύναμη force
πόλη town
σαφή clear
παντρεύομαι marry
χώρα country
παρόν present
μέσα inside
πάτωμα floor
δάχτυλο finger
σχίσιμο tear
δρόμος street
κυρία lady
φόβος fear
κάποιος someone
επιχείρηση business
ικανός able
καρέκλα chair
εξουσία power
ίσως perhaps
μικρός short
έδαφος ground
αληθης true
χείλος lip
πραγματικός real
μήνας month
αργά late
σχολείο school
είτε either
ποιόν whom
χαμηλός low
αναμεταξύ among
σύζυγος husband
διαφορετικός different
ρίχνω drop
ξαφνικά suddenly
χαρτί paper
γη land
είδος sort
συχνά often
απόγευμα evening
εκατό hundred
κόρη daughter
γραφείο office
κρύο cold
φιγούρα figure
δρόμος road
συναισθημα feeling
αριθμός number
πρόστιμο fine
πόλη city
αρκετά several
φτωχός poor
βέβαιος certain
σχέδιο plan
πιθανώς probably
πριν ago
μπλουζα top
μπαίνω enter
έτοιμος ready
μπλε blue
αδελφή sister
κατάσταση state
ωστόσο however
ισχυρός strong
κομμάτι bit
πόδι leg
αγαπητός dear
χαρούμενος happy
όνειρο dream
σημείωση note
λανθασμένος wrong
ενδιαφέρον interest
αίμα blood
γρήγορα quickly
άνεμος wind
αρχοντας lord
δέκα ten
αμφιβολία doubt
είκοσι twenty
κύριε sir
πανεμορφη beautiful
πόλεμος war
αρκετά pretty
αργά slowly
δυνατόν possible
ταλαιπωρία trouble
ευκαιρία chance
ελεύθερος free
αναπνοή breath
κομμάτι piece
ήλιος sun
αλήθεια truth
αν whether
εαυτό itself
ούτε nor
σημάδι sign
συμφωνία deal
ποτήρι glass
δουλειά job
μορφή form
εύκολος easy
ηλικία age
εικόνα picture
έξι six
τελικά finally
σιωπή silence
σκύλος dog
θέαμα sight
αυτί ear
πλοίο ship
προς towards
θάλασσα sea
δαχτυλίδι ring
υπόσχομαι promise
σηκώνω lift
χίλια thousand
γωνία corner
θέα view
πρόβλημα problem
δίπλα beside
τηλέφωνο phone
προσοχή attention
κρυβω hide
βλέμμα gaze
αστυνομία police
κόμμα party
αγγλικά english
πέτρα stone
λονδίνο london
παράξενος strange
μωρό baby
φοβισμένος afraid
πόνος pain
κύμα wave
κουζίνα kitchen
πράσινος green
ζευγάρι couple
συγνώμη sorry
εμπειρία experience
έως till
αμερικανός american
μπορεί maybe
έδρα seat
πράγματι indeed
φυσάω blow
βαρύς heavy
ψυχή soul
σπουδαίος important
παιδί kid
ζεστός warm
θέση position
ζεστό hot
γιατρός doctor
πέρα beyond
θέμα subject
δείπνο dinner
πνεύμα spirit
απόγευμα afternoon
αξιωματικός officer
ησυχια quiet
επιθυμία desire
εκτός except
γη earth
φαντάζομαι imagine
λαιμός neck
μίλι mile
τρόπος manner
φαγητό food
κτίριο building
άκρη edge
πεδίο field
φύση nature
ποτάμι river
βράχος rock
όπλο gun
ευθεία straight
ευρύς wide
εταιρία company
ουρανός sky
ξύλο wood
χορεύω dance
πλήθος crowd
σύντροφος fellow
έκφραση expression
κουτί box
έλεγχος control
εκκλησία church
ολοι everyone
διαλέγω choose
μοιράζομαι share
βασιλιάς king
όμορφη nice
χτίζω build
σχεδόν nearly
μνήμη memory
ρούχα clothes
απλά simply
δέρμα skin
μυστικό secret
σίγουρα certainly
παιχνίδι game
συνομιλία conversation
σκάφος boat
αδειάζω empty
σήμερα today
κόλαση hell
μαλακός soft
τόνος tone
κατεύθυνση direction
απόπειρα attempt
ομάδα group
μάγουλο cheek
τσέπη pocket
ναί yes
μυρίζω smell
άνοιξη spring
γενικός general
μεσαία middle
λογαριασμός account
αριστερά left
ακριβώς exactly
υπηρεσία service
επομενο following
χρέωση charge
δημόσιο public
ευχαρίστηση pleasure
κύριος gentleman
χρυσός gold
οτιδήποτε whatever
νέα news
γόνατο knee
λαμπρός bright
αμέσως immediately
χαρούμενος glad
γρήγορα fast
μονόκλινο single
πράγματι actually
απόσταση distance
σημείο spot
σκηνή scene
απαιτώ demand
τρένο train
τάξη class
ζώο animal
γραφείο desk
αίθουσα hall
στήθος chest
κύριος master
καφές coffee
φρουρά guard
σιωπηλός silent
αποτέλεσμα effect
σκιά shadow
τσάντα bag
ψηλός tall
κανένας none
βουνό mountain
στρατιώτης soldier
μπαρ bar
ιστορία history
καθαρη clean
γάμος marriage
δράση action
χωριό village
μέλος member
μελλοντικός future
λόφος hill
ειδικά especially
κήπος garden
γλυκός sweet
βροχή rain
χαρακτήρας character
ταξιδεύω travel
επίθεση attack
καπνός smoke
ασφαλής safe
χώρος space
περιοχή area
παρακάτω below
κατάσταση situation
τριάντα thirty
στεγνός dry
πηδάω jump
επαναλαμβάνω repeat
άγριος wild
αγγλία england
τέχνη art
εμπρός ahead
τρίτος third
γρήγορα quick
πουκάμισο shirt
μύτη nose
καλοκαίρι summer
λαιμός throat
προσπάθεια effort
απλός simple
όρος term
αγώνας race
αργός slow
καθήκον duty
μουσικη music
ινδός indian
εκδήλωση event
λουλούδι flower
πουλί bird
κύριος mr
δικαστήριο court
συνάντηση meeting
καπέλο hat
σκαρφαλώνω climb
δολοφονία murder
ταιριάζει fit
λεπτός thin
αποτέλεσμα result
βιάζομαι hurry
πλήρης complete
δόντι tooth
σκοπός purpose
σελίδα page
έτσι thus
κοστούμι suit
εχθρός enemy
αιώνας century
συνήθης usual
αντικείμενο object
πλούσιος rich
έκθεση fair
κοινός common
δύναμη strength
πυκνός thick
υλικό stuff
σεβασμός respect
ζωή living
επτά seven
αυλή yard
καφέ brown
εντολή command
παρουσία presence
παλτό coat
σταθμός station
απαραιτητη necessary
τράπεζα bank
τέλειος perfect
αιφνίδιος sudden
οκτώ eight
μονοπάτι path
ιδιαιτερος particular
σκοτάδι darkness
σκαλί stair
κίνηση movement
δύσκολος difficult
κατάστημα shop
χλωμός pale
γλώσσα language
ειδικός special
σοβαρός serious
στενός narrow
κατάσταση condition
αστέρι star
μπουκάλι bottle
ζωντανός alive
κλειδί key
μεγαλόφωνος loud
ήσυχα quietly
λάθος mistake
παρατηρώ observe
ομορφιά beauty
προσεκτικά carefully
πύλη gate
ενήμερος aware
εντελώς completely
υπηρέτης servant
κύκλος circle
ρεκόρ record
τσάι tea
θυμωμένος angry
προσωπικός personal
σύννεφο cloud
κανόνας rule
μάχη battle
σανίδα board
ιδιωτικός private
πληγή wound
φυσικός natural
κάπου somewhere
εμπρός forth
γεύση taste
εύκολα easily
πλάσμα creature
μήκος length
κατάστημα store
φρέσκο fresh
κρασί wine
διαμέρισμα apartment
ευκαιρία occasion
εικόνα image
σύστημα system
δικαστής judge
γλώσσα tongue
λίβρα pound
φλιτζάνι cup
σχήμα shape
αξία worth
τραγούδι song
απόψε tonight
χιόνι snow
επίπεδο level
ανόητος fool
επομένως therefore
άρρωστος sick
κοινωνικός social
αύριο tomorrow
λεπτομέρεια detail
γνώμη opinion
δολάριο dollar
τεράστιος huge
δροσερός cool
στήθος breast
ελαφρώς slightly
κατασκήνωση camp
παράδειγμα example
ταξίδι trip
ξενοδοχειο hotel
ζεύγος pair
ιστορία tale
πιθανός likely
συνήθως usually
αδύνατο impossible
τρομερός terrible
κοινωνία society
ειρήνη peace
μήνυμα message
υπνοδωμάτιο bedroom
υπόθεση affair
παπούτσι shoe
θερμότητα heat
χρώμα color
στρατός army
ξένος stranger
απασχολημένος busy
γκρί gray
γερμανός german
κίτρινος yellow
κάρτα card
αιχμηρός sharp
ηρεμία calm
μπάλα ball
κίνδυνος danger
ολόκληρος entire
απλώς merely
ψάρι fish
κύριος main
συντάκτης author
θόρυβος noise
θυμός anger
διαφορά difference
επισκέπτης guest
σοκ shock
βολή shot
αρχηγός chief
κυβέρνηση government
πενήντα fifty
τρύπα hole
συγγραφέας writer
επιλογή choice
ασημί silver
τύπος type
μικροσκοπικό tiny
γρασίδι grass
εμφάνιση appearance
αμερική america
υπέροχο wonderful
νοσοκομείο hospital
της hers
απαλά gently
μαλακά softly
κομμάτι track
κακό evil
γνώσης knowledge
εξοικειωμένοι familiar
θεό god
περίοδο period
μπλοκ block
σαφώς clearly
ροή stream
περιστατικό circumstance
τρίμηνο quarter
απλό plain
επίπεδη flat
ζήτημα issue
βάση base
απόλαυση delight
νησί island
παρίσι paris
ευκαιρία opportunity
φυτών plant
χαρά joy
σχέση relationship
μαχαίρι knife
ελαφρά slight
βλασφημία damn
διάφορα various
αξία value
πάρκο park
σεξ sex
τοπικά local
νεολαία youth
πρακτική practice
δικαίου wet
πρωινό breakfast
καπετάνιος captain
ταξίδι journey
κυριακή sunday
δεσμεύεται bound
άνεση comfort
χειρονομία gesture
ιερέας priest
γαλλία france
μάρτυρας witness
χαρακτηριστικό feature
κοιμάται asleep
ταιριάζει match
σφιχτά tight
δάσος forest
έλλειψη lack
σύντροφος companion
απόφασης decision
διαδρομή trail
συγκίνηση emotion
οστών bone
ώρα o’clock
τελικό final
επιφάνεια surface
κουτιά dozen
όπλο weapon
κέντρο center
καλωσορίστε welcome
έγκλημα crime
βάρος weight
εραστής lover
σπαθί sword
λίστα list
ημερομηνία date
ομιλία speech
κίνηση motion
πάθος passion
χάρη sake
επιρροή influence
ταχύτητα speed
λαϊκό folk
καταιγίδα storm
πολιτική political
μηχανή machine
σαράντα forty
εννέα nine
βόρεια north
θείος uncle
αρχαία ancient
λυπημένος sad
βρετανός british
λιποθυμία faint
διπλό double
μεσημεριανό lunch
στιγμιαία instant
πλάκα plate
τέλεια perfectly
ωραία lovely
πάγο ice
ληστεία roof
ιντσών inch
οδηγό driver
καθρέφτη mirror
στομάχι stomach
είναι being
εντάξει okay
κανείς nobody
απέναντι opposite
βάρκα boot
σκόνη dust
άμεσα directly
λάμψη glow
άτομο individual
νοσοκόμα nurse
κα. mrs
όραμα vision
περήφανος proud
τρελός mad
αρχή authority
επικοινωνία contact
εφημερίδα newspaper
χριστούγεννα christmas
κινδύνου risk
ιδιαίτερα particularly
βαθμό degree
πρώην former
κάπως somewhat
στυλ style
κάποιος somebody
φορτηγό truck
ενδιαφέρουσα interesting
αστείο joke
ιδιοκτησίας property
γυμνό bare
σάρκα flesh
ανακούφιση relief
λαβή grip
εφοδιασμού supply
γεύμα meal
ξάδερφος cousin
διαδικασία process
θηλυκό female
απώλεια loss
τσιγάρο cigarette
σιδήρου iron
ξεχωριστά apart
φανταχτερό fancy
σειρά row
ρυθμό pace
ασθενή patient
μέγεθος size
γάμος wedding
γέλιο laughter
φύλλο sheet
σχεδιασμό design
σας thy
τροχού wheel
επιτυχία success
επικίνδυνη dangerous
νότια south
ξύπνιοι awake
χαλαρά loose
ευρεία broad
έρημο desert
εγκεφαλικό stroke
πτέρυγα wing
σωρό pile
φλόγα flame
είσοδος entrance
κύριε lord
ομαλή smooth
ισχυρό powerful
κόστος cost
πίστη faith
γέφυρα bridge
φοιτητής student
μέτρο measure
τυφλή blind
όλοι everybody
περιουσία fortune
οφείλεται due
ευγενής gentle
τρελό crazy
διασκέδαση fun
υπερηφάνεια pride
αρσενικό male
δοκιμή test
πλαίσιο frame
πραγματικότητα reality
καθαρό proper
αγρόκτημα farm
ομάδα team
καιρός weather
δυσκολία difficulty
αδύναμη weak
σημαίνει meaning
πτήση flight
ευχάριστη pleasant
κατάστρωμα deck
προσεκτικοί careful
τετράγωνο square
δικαιολογία excuse
επιχείρηση firm
υποκατάστημα branch
τιμή price
πρωτότυπο original
δώδεκα twelve
δικηγόρο lawyer
ίχνος trace
προσευχή prayer
καθένας anybody
τιμή honor
κουδούνι bell
δώρο gift
χριστός christ
ενέργειας energy
ενδεχομένως possibly
συνήθεια habit
πρόθυμος willing
ποιότητα quality
πετάξτε toss
σφάλμα fault
σίγουρα surely
προφανώς apparently
αρχή beginning
όμορφος handsome
βαθιά deeply
φυλακισμένο prisoner
τσάι thee
σακάκι jacket
ήρωας hero
τύχη luck
περιεχομένου content
ευτυχία happiness
πραγματικά truly
πηγούνι chin
ηγέτης leader
χθες yesterday
δεκαπέντε fifteen
ξύλινα wooden
πράκτορα agent
υλικό material
απάντηση response
διέλευση passage
ηλίθιος stupid
μόδα fashion
εργασία task
περίεργο curious
σοφός wise
ποσό amount
τηλέφωνο telephone
δικαίου law
κοινότητα community
φυσική physical
πηγή source
φοίνικα palm
δάσκαλος teacher
σκλάβος slave
λιπαρά fat
στρατιωτική military
ψωμί bread
καμπίνα cabin
πλήρως fully
ανίκανος unable
μάζα mass
αίτημα request
περίεργο odd
ακτή shore
χρυσό golden
απλά mere
σχέση relation
ποσοστό rate
αρκούδα beer
απομακρυσμένη distant
προφανές obvious
σχόλιο comment
ευγενής noble
πλεονέκτημα advantage
φονιά spite
αρχείου file
δυνατότητα possibility
σύγχρονη modern
οθόνη screen
ύπαρξη existence
άμμο sand
θύμα victim
άκρη tip
τρέλα rage
μετρητή counter
ατύχημα accident
εντύπωση impression
ομοφυλόφιλος gay
παραλία beach
θεία aunt
πόρτα doorway
άνετα comfortable
κρίμα pity
προφανώς obviously
διαφορετικά otherwise
εμπόριο trade
κυττάρων cell
υγεία health
δυτικά west
δέρμα leather
τραχύ rough
ζώνη band
πρόταση sentence
διάθεση mood
άρθρο article
αλυσίδα chain
μεταφοράς carriage
σκιά shade
αεροπλάνο plane
κολέγιο college
ποίημα poem
σχοινί rope
λάμπα lamp
παράδειγμα instance
καθαρό pure
πίσω rear
ειλικρινής honest
σημαντικός major
παρόμοια similar
δραστηριότητα activity
διάσημο famous
άγχος anxious
αστείο funny
επιχείρημα argument
διάβολος devil
εμπιστοσύνη confidence
ιδρώτα sweat
ρωσικά russian
περιοχή range
συναγερμού alarm
τρόμου horror
ασφάλεια security
πληρώματος crew
αυγή dawn
έθνος nation
μέταλλο metal
νευρικό nervous
φυλακή prison
οπουδήποτε anywhere
ποιητής poet
του sin
στάση attitude
δήλωση statement
γυμνός naked
νομοσχέδιο bill
μέτωπο brow
ηθική moral
rolle role
αφθονία plenty
σταδιοδρομία career
ουρά tail
γέννηση birth
επίσημες official
μοίρα fate
σχέδιο project
κοιλάδα valley
φαντασία imagination
αγορά market
γροθιά fist
πρόθεση intention
σύνδεση connection
σειρά series
θάρρος courage
πύργος tower
λίμνη lake
ταινία movie
φούστα skirt
θάλαμος chamber
δίκη trial
μαγεία magic
μηχανή engine
ευχαριστίες thanks
γραφή writing
κουμπί button
ταινία film
συνήθης ordinary
θεωρία theory
κανονικός normal
σταθερός steady
ιούνιος june
εβραίος jew
κείμενο text
απολύτως absolutely
τιμή honour
μυστήριο mystery
εποχή season
ιδιοκτήτης owner
χρώμα colour
συμβουλή advice
εταίρος partner
καπάκι cap
ελευθερία freedom
προσωπικό staff
κατόπιν afterwards
σωστός correct
πισίνα pool
σήμα signal
αθώος innocent
φτέρνα heel
γενικά generally
κουρτίνα curtain
κατοχή possession
φωτογραφία photograph
μόλις scarcely
ραδιόφωνο radio
ντόπιος native
γκρί grey
μορφή blanket
συνέντευξη interview
βρώμικος dirty
ντροπή shame
αυγό egg
εξήγηση explanation
κάρο wagon
ακροατήριο audience
απαίσιος awful
σωλήνας pipe
καλλιτέχνης artist
μυθιστόρημα roman
ύφασμα cloth
τρόμος terror
όγκος volume
ανατολή east
τμήμα section
τάξη rank
φιλικός friendly
πεινασμένος hungry
επισκέπτης visitor
παντού everywhere
θρησκευτικός religious
κρέας meat
υπηρέτρια maid
δικαιοσύνη justice
πρόοδος progress
αγκαλιά lap
επάνω upstairs
πίστη belief
μυθιστόρημα novel
φάντασμα ghost
σάββατο saturday
χειρουργική operation
πια anymore
trots despite
μέση waist
γάλα milk
τουαλέτα bathroom
κατσαρόλα pot
περιουσία estate
προηγούμενος previous
μυθιστόρημα fiction
μεγαλοπρεπής grand
παγίδα trap
τέχνασμα trick
φάρμακο drug
μετάξι silk
σούπες supper
μεθυσμένος drunk
υπαινιγμός hint
αγανάκτηση harm
καρπός fruit
υπολογιστή computer
αγκώνα elbow
βεράντα porch
ups upper
μπάτσος cop
παππούς grandfather
άσκηση exercise
βιβλιοθήκη library
μυς muscle
ευρώπη europe
εύνοια favor
ρίζα root
θηρίο beast
πρόκληση challenge
ντους shower
ελληνικά greek
παντού throughout
σεξουαλικός sexual
κορδόνι string
όριο limit
εστιατόριο restaurant
θρησκεία religion
πίεση pressure
χάρη grace
απέραντος vast
θυσία sacrifice
άφιξη arrival
μάθημα lesson
ισχίο hip
άδεια lad
λάδι oil
πρότυπο pattern
τακτικός regular
τουφέκι rifle
τυχερός lucky
γάιδαρος ass
αμβλύς dull
συνειδητός conscious
χάος mess
στοιχείο element
konsekvens consequence
ισορροπία balance
αρχή principle
στοργή affection
ρεύμα current
κερί candle
σκατά shit
ύψος height
στοκ stock
ιππότης knight
ρολόι clock
κάστρο castle
φράκτης fence
ένοχος guilty
ναός temple
εκτός besides
περιοδικό magazine
αγαπημένη favorite
κάθονται seated
απρίλιος april
παράδοση tradition
πικρός bitter
επιστήμη science
δημοφιλής popular
γιαγιά grandmother
μοντέλο model
καθημερινά daily
συζήτηση discussion
πρίγκιπας prince
γοητεία charm
στολή uniform
περιγραφή description
οροφή ceiling
θάμνος bush
λαθος false
ενδιαφέρεστε interested
στενά closely
πάγκος bench
γενναίος brave
ικανοποίηση satisfaction
λεωφορείο bus
λογοτεχνικός literary
αιματηρός bloody
αλλοδαπός foreign
στυλό pen
θλίψη grief
βοήθεια aid
φιλία friendship
περιπέτεια adventure
κουλτούρα culture
ακτίνα beam
ασφάλεια safety
πορεία march
γυαλιά glasses
evne ability
άριστη excellent
σταθερά firmly
κατανόηση understanding
χάλυβας steel
νεύρο nerve
άγγελος angel
γίγαντας giant
υποψία suspicion
άγνωστος unknown
ίσος equal
σκηνή tent
έξυπνος smart
γενεά generation
ανά per
σημάνει spell
αντίδραση reaction
εκπαίδευση education
απόδειξη proof
λεκάνη bowl
προειδοποίηση warning
βάθος depth
κεφάλαιο chapter
διευθέτηση arrangement
βαριά heavily
ιταλικά italian
φρύδι eyebrow
παλάτι palace
σοβαρά seriously
ζωγραφική painting
viktigheten importance
επιπλέον extra
βασίλισσα queen
σιωπηλά silently
καρπό wrist
ευθύνη responsibility
εντελώς altogether
σαγόνι jaw
κακώς badly
επιβάτης passenger
άνοιγμα opening
ιούλιος july
επιδεξιότητα skill
αποστολή mission
έθιμο custom
μέθοδος method
αγελάδα cow
πρόθυμος eager
πολεμιστής warrior
σπηλιά cave
πίστωση credit
έπαινος praise
ικανός capable
εκδοχή version
γείτονας neighbor
συμπάθεια sympathy
σύρμα wire
περιέργεια curiosity
ζώνη belt
σχετικός relative
έννοια notion
ταχυδρομείο mail
καναπές couch
διάδρομο corridor
ισπανικά spanish
απειλή threat
κινέζικα chinese
υψηλά highly
τελικά eventually
σύνδεσμος link
απουσία absence
απελπισία despair
δομή structure
μοναχικός lonely
ευγνώμων grateful
χάρτης map
υπουργός minister
μαξιλάρι pillow
ορατός visible
πλοίο vessel
ερωμένη mistress
λεπτός delicate
επαγγελματίας professional
ζεστασιά warmth
σπασμένος broken
ανόητος silly
ντετέκτιβ detective
λύπη sorrow
σέλλα saddle
βλάβη damage
όμορφη rare
φόρεμα gown
στερεός solid
εξαιρετικά extremely
φράση phrase
καρφί nail
αύγουστος august
εργάτης worker
σφαίρα bullet
κορμός trunk
konkluderer conclusion
όπλο pistol
λαμπρός brilliant
πολίτης citizen
ταχέως rapidly
πρόσφατα recently
απελπισμένος desperate
αβασάνιστα lightly
άποψη aspect
σύγχυση confusion
άσχημος ugly
νοημοσύνη intelligence
κρεβάτι sofa
αγάπη darling
μπαμπάς dad
καμπύλη curve
αεράκι breeze
λίκα equally
ταινία tape
μυρωδιά scent
ανάπτυξη development
ιατρικός medical
κλίση slope
φυσικά naturally
ψυχική mental
βρωμιά dirt
κέλυφος shell
οικόπεδο plot
στέμμα crown
επιτυχής successful
αρετή virtue
πλημμύρα flood
ρώμη rome
πορτοφόλι purse
ποίηση poetry
κοιλιά belly
σύνολο total
κρίση judgment
enorme enormous
μπάσκετ basket
καταφύγιο shelter
ansvarlig responsible
συνείδηση consciousness
senaste recent
εγκληματίας criminal
πολύτιμος precious
αρκετά fairly
σύνορο border
ωκεανός ocean
φύλλα blade
μηρό thigh
αντανάκλαση reflection
κηδεία funeral
τμήμα department
ασυνήθιστος unusual
όχημα vehicle
φόβος dread
φόντο background
πρότυπο standard
τηλεόραση television
εντελώς totally
όφελος benefit
τραπεζαρία dining
